name: Tests

on:
  push:
    branches: [ backport-java21 ]
    paths-ignore:
      - 'README.md'
      - 'readme/**'
  pull_request:
    branches: [ backport-java21 ]
    paths-ignore:
      - 'README.md'
      - 'readme/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: maven

    - name: Build and Test with Maven
      run: mvn clean package
